/**:
  ros__parameters:
    cmd_freq: 100.0  # Hz of platform commands send
    info_freq: 10.0  # Hz of platform info publish
    sensor_freq: 10.0  # Hz of platform sensor publish
    camera_freq: 30.0  # Hz of platform camera publish
    